version: '3.5'
services:
#
# POSTGRESQL
#
  postgres-otrs:
    image: postgres:9.6
    container_name: postgres-otrs
    restart: unless-stopped
    environment: 
      POSTGRES_DB: otrs
      POSTGRES_USER: otrs
      POSTGRES_PASSWORD: otrs
      #    volumes:
      #    - postgresql-otrs-volume:/var/lib/mysql:rw
    networks: 
    - backend    
#
# OTRS
#
  otrs: 
    build: otrs/.
    image: fametec/otrs:6.0.28
    restart: unless-stopped
    container_name: otrs
    environment:
      LANGUAGE: pt_BR
      FQDN: "localhost"
      ADMINEMAIL: "root@localhost"
      ORGANIZATION: "FAMETEC"
      DB_TYPE: postgres 
      DB_NAME: otrs
      DB_USER: otrs
      DB_PASSWORD: otrs
      DB_HOST: postgres-otrs
      #    volumes:
      #    - otrs-volume:/opt/otrs:rw
    depends_on:
    - postgres-otrs
    networks:
    - backend
    - middle
#
# GRAFANA
#
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    container_name: grafana
    depends_on:
    - postgres-otrs
    environment:
      GF_SERVER_DOMAIN: localhost:3000
      GF_SERVER_ROOT_URL: http://localhost:3000/grafana/
      GF_AUTH_BASIC_ENABLED: "true"
      GF_AUTH_PROXY_ENABLED: "true"
      GF_AUTH_PROXY_HEADER_NAME: "X-WEBAUTH-USER"
      GR_USERS_ALLOW_SIGN_UP: "false"
      GF_SECURITY_ADMIN_PASSWORD: secret
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel
    networks: 
    - middle
    - backend
#
# NGINX
#
  nginx:
    image: fametec/nginx
    restart: unless-stopped
    container_name: nginx
    ports:
     - 443:443
    depends_on: 
     - otrs
     - grafana
    networks: 
     - frontend
     - middle
#
#
# PORTAINER
#
#  portainer:
#    image: portainer/portainer
#    container_name: portainer
#    ports: 
#    - 127.0.0.1:9000:9000
#    volumes: 
#    - /var/run/docker.sock:/var/run/docker.sock
#    - portainer_data:/data 
#
#
# VOLUMES
#
#volumes:
#  otrs-volume:
#  postgresql-otrs-volume:
#  portainer_data:
#
# NETWORKS
#
networks: 
  frontend: 
  middle: 
  backend:
